name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create build directory
        if: not fileExists("/path/to/build")
        run: sudo mkdir -p /build

      - name: Check build directory exists
        if: not fileExists("/path/to/build")
        run: test -d /build

      - name: Mount local directory
        run: sudo mount -t ntfs /path/to/build /build

      - name: Build the Docker image
        run: docker build -t my-image-name:$(date +%s) /build/Dockerfile

  run-container:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run the Docker container
        run: docker run -d --name youtube-player my-image-name:$(date +%s)
