
name: Docker Image CI

on:
   schedule:
       # Run the workflow every 2 minutes
       cron: "*/2 * * * *"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
                uses: actions/checkout@v3

            - name: Build container
                run: docker build -t youtube-player .

            - name: Run container
                run: docker run -d --name youtube-player youtube-player



