name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the Docker container
        run: docker run -d --name youtube-player my-image-name
